---
galaxy_info:
  author: Israel Ogbole (https://galaxy.ansible.com/iogbole)
  role_name: common
  company: AppDynamics
  description: This is an AppDynamics helper role, all other agent roles depends on the common role.
  license: Apache2
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
        - xenial
        - artful
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
    - name: EL
      versions:
        - 8
        - 7
        - 6
    - name: Windows
      versions:
        - 2008x64
        - 2008R2
        - 2012
        - 2012R2
        - 2016
        - 2019
  galaxy_tags:
    - apm
    - monitoring
dependencies: []