---
galaxy_info:
  author: israel.ogbole
  role_name: win_pkg
  company: AppDynamics
  description: This is an AppDynamics Windows package role, Installations on Windows inherits tasks from this role
  license: Apache2
  min_ansible_version: 2.8
  platforms:
    - name: Windows
      versions:
        - 2008x64
        - 2008R2
        - 2012
        - 2012R2
        - 2016
        - 2019
  galaxy_tags:
    - apm 
    - monitoring
dependencies: []