---

# DB Agent Linux
db_agent_dest_folder_linux: /opt/appdynamics/db-agent
db_agent_dest_file: db-agent.zip

# Machine Agent Win
machine_agent_dest_folder_win: C:/appdynamics/machine-agent
machine_agent_monitor_folder_win: "{{ machine_agent_dest_folder_win }}\\monitor"
temp_dir: /tmp

# Machine Agent Linux
machine_agent_dest_folder_linux: /opt/appdynamics/machine-agent
machine_agent_monitor_folder_linux: "{{ machine_agent_dest_folder_linux }}/monitor/"

# Machine Common 
ma_agent_dest_file: machine-agent.zip
machine_agent_hierarchy_root: ACME 

# DotNet Agent Win
dot_agent_dest_folder_win: C:\\appdynamics\\dotnet-agent # '/' does not work with win_package
dotnet_agent_dest_file: dotNetAgentSetup64.msi

# Java Agent Linux 
java_agent_dest_folder_linux: /opt/appdynamics/java-agent
app_agent_dest_file: java-agent.zip
