---
#wheel user for Machine agent
appdynamics_user: appdynamics
############ DO NOT CHANGE ANY OF THESE DEFAULTS - Except you know what you're doing#######################
java_system_properties: ""
host_name: '{{ ansible_hostname }}' # computername/hostname of the target machine

#Agent Log level
agent_log_level: "info"
agent_loggers: ['com', 'com.singularity']

# Analytics agnent location
analytics_agent_host: localhost
analytics_agent_port: 9090

#windows_ma_finder_string
win_ma_finder_string: machineagent-bundle-64bit-windows
win_db_finder_string: db-agent-winx64
linux_ma_finder_string: machineagent-bundle-64bit-linux
linux_db_finder_string: db-agent

# Machine Common
ma_agent_dest_file: machine-agent.zip
machine_hierarchy: ""

#controller defaults
enable_ssl: false
enable_proxy: false
enable_proxy_authentication: false
