---
galaxy_info:
  author: israel.ogbole
  role_name: linux_pkg
  company: AppDynamics
  description: This is an AppDynamics linux package helper role, all installations on Linux depends on this role. 
  license: Apache2
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
        - xenial
        - artful
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
    - name: EL
      versions:
        - 8
        - 7
        - 6
        
  galaxy_tags:
    - apm 
    - monitoring
dependencies: []