
- name: Set the unique host id so that machines appear correctly for APM
  win_environment:
    state: present
    level: machine
    name: "APPDYNAMICS_AGENT_UNIQUE_HOST_ID"
    value: "{{ ansible_hostname }}"

- name: DotNet Agent Java Agent
  include: dotnet-agent.yml


- name: Clean up - remove {{ dotnet_agent_dest_file }} 
  win_file:
    path: "{{ dot_agent_dest_folder_win }}\\{{ dotnet_agent_dest_file }}"
    state: absent
