# Java Agent Linux
#java_agent_dest_folder_linux: /opt/appdynamics/java-agent
java_agent_dest_file: java-agent.zip

# Java Agent Windows
#java_agent_dest_folder_win: C:/appdynamics/java-agent

create_appdynamics_user: yes
agent_dir_permission:
  user:  "{{ appdynamics_user }}"
  group: "{{ appdynamics_user }}"

node_name: "{{ host_name }}-{{ tier_name }}"

#add application details (app/tier/node) into controller-info.xml.
application_details_in_config: yes