- name: "Get AppDynamics Agent Download URL type:{{ agent_type}}, version: {{ agent_version }}"
  shell: "{{role_path}}/files/get-agent.sh download {{ agent_type }} -v {{ agent_version }} --dryrun"
  register: agent_download_url
  #delegate_to: localhost
  failed_when:
   (agent_download_url.rc != 0) or 
   (agent_download_url.stderr != '') or 
   (agent_download_url.stdout is not match("https://download-files.appdynamics.com/download-file/"))
   
- debug: 
   msg: "{{ agent_download_url.stdout }}"

