---
- debug:
   msg: "{{ agent_type|lower }}"

- name: Validate agent_type
  assert:
    that:  agent_type is defined
    msg: 'agent type must be provided. Refer to https://github.com/Appdynamics/download-appdynamcis-agents#supported-agent-types'

- name: "Validate agent_version"
  assert:
    that:  agent_version is defined
    msg: 'The version of the agent must be provided.'

- name: Validate application_name
  assert:
    that:  application_name is defined
    msg: 'An application_name must be provided'
  when: "agent_type not in ('machine.*,db.*')"

- name: Validate tier_name 
  assert:
    that:  tier_name is defined
    msg: 'A tier name must be provided'
  when: "agent_type not in ('machine.*,db.*')"

- name: Validate controller_account_access_key
  assert:
    that:  controller_account_access_key is defined
    msg: 'A controller_account_access_key must be provided'

- name: Validate controller_global_analytics_account_name
  assert:
    that:  controller_global_analytics_account_name is defined
    msg: 'A controller_global_analytics_account_name must be provided'
  when: enable_analytics_agent == true

- name: Validate controller_host_name
  assert:
    that:  controller_host_name is defined
    msg: 'A controller_host_name must be provided'

- name: Validate controller_account_name
  assert:
    that:  controller_account_name is defined
    msg: 'A controller_account_name must be provided'

- name: Validate controller_port
  assert:
    that:  controller_port is defined
    msg: 'A controller_port must be provided'
    
- name: Validate analytics_event_endpoint
  assert:
    that:  analytics_event_endpoint is defined
    msg: 'A analytics_event_endpoint must be provided'
  when: enable_analytics_agent == true
