---
agents_to_set_loggers_for: [] # Initialize to an empty list
agent_loggers: ['com', 'com.singularity']
agent_log_level: "info"

#Internal variables.
agent_folder_exists: true # default to true for when the dir is not explicitly checked
logger_must_check_if_agent_dir_exists: true # set to false when you know the directory exists (like when installing an agent)
