name: "appdynamics.agents.java"
on:
  push:
    paths:
      - 'roles/java/**'
      - 'molecule/java/**'
      - '.github/workflows/java.yml'
      - 'roles/common/**'
  pull_request:
    paths:
      - 'roles/java/**'
      - 'molecule/java/**'
      - '.github/workflows/java.yml'
      - 'roles/common/**'
jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      matrix:
        distro:
          - centos8
          #- ubuntu
        collection_role:
          - java
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
          docker_nightly_version: snapshot-20201008
      - run: |
          set -x
          docker version

      - name: Install test dependencies.
        run: pip3 install molecule docker yamllint ansible-lint
      
      - name: Build the collection
        run: |
          collection_file=$( basename $(ansible-galaxy collection build -f | awk -F" " '{print $NF}'))
          echo "::set-env name=COLLECTION_FILE::$collection_file"
        
      - name: Install the collection
        run: ansible-galaxy collection install ${COLLECTION_FILE}
      
      #- name: Test the collection
      #  run: |
      #     cd /home/runner/.ansible/collections/ansible_collections/appdynamics/agents
      #     ansible-test sanity --docker default -v
      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          molecule --debug test -s ${{ matrix.collection_role }} 
        env: 
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
